[package]
name = "rust-eze"
version = "0.1.0"
edition = "2024"

[dependencies]
postgres = "0.19"
serde = "1.0" # Para serializar y deserializar JSON
serde_json = "1.0"
serde_derive = "1.0"
rand = "0.8" 