version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rust_app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: rust_app
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://user:password@postgres:5432/mydatabase
    ports:
      - "8080:8080"
    volumes:
      - ./rust-eze:/app/rust-eze  
    command: ["cargo", "run"]

volumes:
  postgres_data:
